export const COUNTER = {
    INCREASE: 'INCREASE',
    DECREASE: 'DECREASE'
};

export const TODOS = {
    SET_TODOS: 'SET_TODOS',
    ADD_TODO: 'ADD_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    UPDATE_TODO: 'UPDATE_TODO',
    CLEAN_TODOS: 'CLEAN_TODOS',
}